package stdlib

import (
	"bytes"
	_ "embed"
	"encoding/gob"
	"fmt"
)

type Symbol struct {
	Name      string
	Doc       string
	Signature string
	Kind      string
}

type Package struct {
	Name    string
	Symbols []Symbol
}

//go:embed stdlib.gob
var encoded []byte

// Packages is a list of all the packages in the Gno standard library.
//
// We use it to power live, in-editor intelisense such as:
//
// - Hover tooltips
// - Autocomplete
//
// The list is generated by the `/cmd/gen` command.
var Packages = []Package{}

func init() {
	dec := gob.NewDecoder(bytes.NewReader(encoded))
	if err := dec.Decode(&Packages); err != nil {
		panic(err)
	}
}

func (s Symbol) String() string {
	return fmt.Sprintf("```go\n%s\n```\n\n%s", s.Signature, s.Doc)
}
